<html>
<head>
	<title>The Beerbelly</title>
	
	<link rel="stylesheet" type="text/css" 	href="style.css">
	
	<link rel="icon" href="images/logo.png">
	<meta name='viewport' content='width=device-width, initial-scale=1.0'>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" type="text/css" media="all">
	<script language='javascript' src='ordersubmit.js'></script>

</head>
<body>
	
	<div>
    	<a href="index.html"><img src = "images/logo.png" id="logo"></a> 
    </div>
   
    <div>	
	    <div id="menu">
	   
	   		<ul id="MenuBar">
				<li  class="MenuItem"> <a href="index.html">Home</a> </li>
    			<li  class="MenuItem"> <a href="products.html">Products </a> </li>
    			<li	 class="MenuItem"> <a href="contact.html"> Contact</a></li>
				<li	 class="MenuItem"> <a href="order.html"> Order </a></li>
				<li  class="MenuItem">   <a href='cart.html'> <i class="fa fa-shopping-cart id="CartMenuItem""> Cart </i> </a> </li>
			</ul>
		</div>
	</div>
	
	<div id="content">